[versions]
kotlin = "1.8.10"
ksp = "1.8.10-1.0.9"
androidx-core = "1.8.0"
appcompat = "1.4.1"
activity = "1.6.1"
lifecycle-runtime = "2.5.1"
room = "2.5.2"
material = "1.5.0"
agp = "8.3.0"
threetenabp = "1.4.4"
retrofit = "2.9.0"
okhttp3 = "4.10.0"
timber = "5.0.1"
compose-compiler = "1.4.2"
compose-runtime = "1.3.3"
medivh = "1.2.4"
serialization = "1.8.10"
big-brother="1.1.2"

# confirm
kotlin-reflection = "1.7.21"
kotlin-coroutines = "1.6.1"

[libraries]
# AndroidX
androidx-core = { module = "androidx.core:core-ktx", version.ref = "androidx-core" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
androidx-activity = { module = "androidx.activity:activity-ktx", version.ref = "activity" }
androidx-fragment = { module = "androidx.fragment:fragment-ktx", version.ref = "activity" }
androidx-lifecycle-runtime = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle-runtime" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }

# Material
material = { module = "com.google.android.material:material", version.ref = "material" }

# Kotlin
kotlin-reflection = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin-reflection" }
kotlin-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlin-coroutines" }
kotlin-serialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version = "1.3.3" }

# Squareup
squareup-retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
squareup-retrofit-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }
squareup-okhttp3 = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp3" }
squareup-okhttp3-logging = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp3" }

# Compose
compose-material3 = { module = "androidx.compose.material:material", version = "1.3.1" }
compose-runtime = { module = "androidx.compose.runtime:runtime", version.ref = "compose-runtime" }
compose-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "compose-runtime" }
compose-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose-runtime" }
compose-activity = { module = "androidx.activity:activity-compose", version = "1.6.1" }

# Others
jakewharton-threetenabp = { module = "com.jakewharton.threetenabp:threetenabp", version.ref = "threetenabp" }
gson = { module = "com.google.code.gson:gson", version = "2.10.1" }
timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }

# AGP
agp-core = { group = "com.android.tools.build", name = "gradle", version.ref = "agp" }
agp-api = { group = "com.android.tools.build", name = "gradle-api", version.ref = "agp" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
android-kotlin = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
medivh = { id = "tech.medivh.plugin.publisher", version.ref = "medivh" }
serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "serialization" }
plugin-publish = { id = "com.gradle.plugin-publish", version = "1.2.1" }
deeplink = { id = "io.github.mrocigno.extract.deeplink", version.ref = "big-brother" }
