name: Publish package to the Maven Central Repository

on:
  pull_request:
    types: [opened]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Assemble and publish
      uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25 # v2.6.0
      with:
        arguments: |
          assemble
          publish
          -Psigning.keyId=${{ secrets.KEY_ID }}
          -Psigning.password=${{ secrets.SIGNING_PASSWORD }}
          -Psigning.secretKeyRingFile=/home/runner/work/big-brother/big-brother/sandman.gpg
      env:
        ossrh_username: ${{ secrets.OSSRH_USERNAME }}
        ossrh_password: ${{ secrets.OSSRH_PASSWORD }}