name: Publish package to the Maven Central Repository

on:
  push:
    branches:
      - 'main'

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Assemble and publish
      uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25 # v2.6.0
      with:
        arguments: |
          assemble
          uploadToSonatype
          -Psigning.keyId=${{ secrets.KEY_ID }}
          -Psigning.password=${{ secrets.SIGNING_PASSWORD }}
          -Psigning.secretKeyRingFile=/home/runner/work/big-brother/big-brother/sandman.gpg
          -PsonatypeUsername=${{ secrets.OSSRH_USERNAME }}
          -PsonatypePassword=${{ secrets.OSSRH_PASSWORD }}
